### ISSUE TITLE
1.2.alpha2 fails on install

### ISSUE THREAD

**Issue by bkaless** [systopia/de.systopia.campaign#70] opened 2018-01-26 08:00 UTC
Installing the 1.1.alpha2 brings the following error in the apache2.log:

PHP Fatal error:  Class 'CRM_Campaign_Config' not found in /var/www/html/sites/default/files/civicrm/ext/de.systopia.campaign/campaign.php on line 45,

**Comment by bkaless** [comment] 2018-01-26 08:21
Oh, I see this Issues points to the same question: 
https://github.com/systopia/de.systopia.campaign/issues/61

**Comment by jensschuppe** [comment] 2018-09-21 12:43
Closing as duplicate of #61.

**Closed as completed by jensschuppe** 2018-09-21 12:43 UTC
Labels: duplicate
