### ISSUE TITLE
extension enabled, but civicrm/a/#/campaign/<id>/view empty

### ISSUE THREAD

**Issue by bkaless** [systopia/de.systopia.campaign#3] opened 2015-11-19 11:27 UTC
I enabled the extension, created a campaign. The page, the view link refers to is empty.

**Comment by bjendres** [comment] 2015-11-19 11:48
@bkaless Could you post the whole link? It might have to do with AnglularJS - you're on 4.6+ right?

**Comment by bkaless** [comment] 2015-11-19 11:54
Yes, we are on 4.6.

It is in our test-system: <url>civicrm/a/#/campaign/2/view

**Comment by bjendres** [comment] 2015-11-19 14:46
Are you sure that the Campaign module is enabled, and your user has the appropriate campaign-permissions? Can you see the "Campaign" menu?

**Comment by bkaless** [comment] 2015-11-19 14:50
yes. Campaign is activated, I see the "Campaign" menu. My user has id 1, the permissions for civicampaign are okay.

**Comment by bjendres** [comment] 2015-11-19 14:51
Could you reload with a dev console (like Firebug) open, and see if there is an error message?

**Comment by bkaless** [comment] 2015-11-19 15:39
yes, indeed. Tere is a error: . 

Error: [$injector:modulerr] Failed to instantiate module crmApp due to:
[$injector:modulerr] Failed to instantiate module campaign due to:
[$injector:nomod] Module 'campaign' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

I suppose, there is an inconsistency in the sql-Database?

**Comment by bjendres** [comment] 2015-11-19 15:43
@nikobo  Could you have a look?

**Comment by ghost** [comment] 2015-11-19 15:46
I will look into it on monday because I'm not at work tomorrow.

**Comment by ghost** [comment] 2015-11-23 09:42
@bkaless Could you tell me which specific version of CiviCRM you are using? Is it > 4.6.8?

**Comment by bkaless** [comment] 2015-11-23 09:51
it is 4.6.10.

do you have an account for our test-system?

**Comment by ghost** [comment] 2016-01-18 11:44
I just checked your test environment. The problem is the following:

de.systopia.campaign uses html templates that are stored in the [/partials](https://github.com/systopia/de.systopia.campaign/tree/master/partials) directory and are dynamically retrieved from the client. The server returned a 404 error for this directory. This can happen if either the **Extension Resource URL** (/civicrm/admin/setting/url) has not been set or is not accessible from the web

**Comment by bkaless** [comment] 2016-01-18 11:52
Oh, it could be so easy. Thanks for your support. The extension works in our environment.

**Comment by ghost** [comment] 2016-01-19 14:51
Sounds good. I will close this issue now. If you need further assistance feel free to open another issue or send me an email.

**Closed as completed by ghost** 2016-01-19 14:51 UTC
Labels: question, wontfix
