### ISSUE TITLE
Breaks Angular

### ISSUE THREAD

**Issue by herbdool** [systopia/de.systopia.campaign#68] opened 2017-11-23 22:45 UTC
I'm testing 1.2 alpha2. The JS errors I'm getting:

`Uncaught TypeError: Cannot set property 'contextMenu' of undefined` in line 889 of `...civicrm/asset/builder&an=angular-modules.js&ap=...`. Does this have something to do with d3?

And `Uncaught Error: [$injector:modulerr]`

I've noticed them in 4.7.23 and 4.7.27 on sites hosted in different environments. It seems to be breaking various pages that rely on Angular, including the system status page: civicrm/a/#/status.

I tried this patch but didn't help: https://github.com/systopia/de.systopia.campaign/issues/65

**Comment by bkaless** [comment] 2017-12-12 10:13
It breaks on 4.7.28 also. 

But in a second environment it runs smoothly.

**Comment by bkaless** [comment] 2018-01-25 16:53
I can describe my experience more precisely: If I make a clone of my productive system I choose a http:// instead a https:// URL as BASEURL in civicrm.settings.php for it. In this case the angular pages works without any further changing in the settings. 

The Web-Konsole in Firefox shows a 404 error for a angular page in the productive system (running with SSL).

**Comment by jensschuppe** [comment] 2018-09-21 12:55
Looks like this is a duplicate of or related to #60, which got merged already.

@bkaless Could you verify that the latest alpha fixes the problem?

**Closed as completed** 2018-09-21 13:19 UTC
Labels: bug, duplicate
