### ISSUE TITLE
1.1alpha1: Sorting

### ISSUE THREAD

**Issue by bkaless** [systopia/de.systopia.campaign#37] opened 2017-05-11 09:29 UTC
Ad the moment the list in the overview is not sorted. It would be fine if  the list is sorted by date (newest beginning date first) by default.

**Comment by bjendres** [comment] 2017-05-11 09:47
@mattwire What was the plan here? Is this list currently sorted by anything?

**Comment by mattwire** [comment] 2017-05-12 22:02
Currently it is sorted by name ascending by default.  But you can sort by any column by clicking on it.

**Comment by jensschuppe** [comment] 2018-09-21 13:12
I can confirm default sorting being name ascending. As the table is sortable, looks like won't fix to me.

**Closed as completed by jensschuppe** 2018-09-21 13:12 UTC
Labels: wontfix
